baseURL = "https://example.org/"
languageCode = "en-us"
title = "Metro Theme for Hugo"
theme = "gohugo-theme-metro"
themesDir = "../.."

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

copyright = "&copy; 2020 Synecdoche Web Services LLC"
[params]
icon = "icon.svg"

[menu]
[[menu.social]]
identifier = "github"
name = "Code on Github"
url = "https://github.com/Synecdoche-Web-Services/gohugo-theme-metro"
